"""add industry types to companies

Revision ID: 246dae09edb0
Revises: 7ad16b756af0
Create Date: 2026-05-05 17:55:40.719345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246dae09edb0'
down_revision: Union[str, Sequence[str], None] = '7ad16b756af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "companies",
    sa.Column(
        "industry",
        sa.Enum("retail", "aviation", name="industry_enum"),
        nullable=False,
        server_default="aviation"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'industry',
               existing_type=sa.Enum('retail', 'aviation', name='Industry_Enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
