"""add flight status

Revision ID: 45a3dbaaf587
Revises: 3140c37c5a4a
Create Date: 2026-05-18 10:33:13.487650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a3dbaaf587'
down_revision: Union[str, Sequence[str], None] = '3140c37c5a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'flights',
        sa.Column(
            'status',
            sa.String(),
            nullable=False,
            server_default='scheduled'
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'status')

    # ### end Alembic commands ###
