"""add updated_at to users

Revision ID: 7ad16b756af0
Revises: 59d6a66ee012
Create Date: 2026-04-17 14:52:02.640381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad16b756af0'
down_revision: Union[str, Sequence[str], None] = '59d6a66ee012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('users_password_hash_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_password_hash_key'), 'users', ['password_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
